"""
TYPE LIST
"""
LIST_TYPE_PRESENTER = 'PRESENTER'
LIST_TYPE_VIDEO = 'VIDEO'
LIST_TYPE_IMAGE = 'IMAGE'
LIST_TYPE_CAMERA = 'CAMERA'
LIST_TYPE_SCHEDULE = 'SCHEDULE'
LIST_TYPE_AUDIO = 'AUDIO'

"""
TYPE SOURCE
"""
SOURCE_TYPE_IMAGE = 'IMAGE'
SOURCE_TYPE_TEXT = 'TEXT'

"""
TYPE MODE
"""
MODES = ['NORMAL','ONLYMAIN']
MODES_NORMAL = 'NORMAL'
MODES_ONLYMAIN = 'ONLYMAIN'